#!/usr/bin/env python3
"""Render 47 tactical cards as a compact LaTeX appendix file.

Output: paper/tactical_cards_appendix.tex
"""
import json
import sys
from pathlib import Path

ROOT = Path('/home/ntu/zqh/research/novelty_skill')
sys.path.insert(0, str(ROOT / 'paper'))
from render_cards import latex_escape

CARDS = ROOT / 'data' / 'clustering' / 'tactical_cards' / 'tactical_cards.json'
TAX_PATH = ROOT / 'data' / 'clustering' / 'results' / 'methodologies.json'
OUT = ROOT / 'paper' / 'tactical_cards_appendix.tex'


def render_card(c):
    cid = c['cluster_id']
    label = c['cluster_label']
    s = c['meta']['sample_sizes']
    card = c['card']
    title = (
        f'\\textbf{{C{cid:02d}}}: {latex_escape(label)} '
        f'\\textcolor{{gray}}{{\\small (O{s["oral"]}/H{s["hc"]}/R{s["reject"]}, conf: '
        f'\\textbf{{{card["confidence"]}}})}}'
    )
    out = []
    out.append(
        '\\begin{tcolorbox}[colback=bgskill!50, colframe=cgreen!70, '
        'title={' + title + '}, breakable, before skip=4pt, after skip=4pt]'
    )
    out.append(f'\\textbf{{Tactical pattern.}} {latex_escape(card["tactical_pattern"])}')
    out.append('')
    out.append(f'\\textbf{{Differentiation.}} \\textit{{{latex_escape(card["differentiation_within_parent"])}}}')
    out.append('')
    out.append(f'\\textbf{{When to pick.}} {latex_escape(card["when_to_pick_this_one"])}')
    out.append('')
    out.append(f'\\textbf{{Tactical failure.}} {latex_escape(card["tactical_failure_mode"])}')
    out.append('')
    out.append('\\textbf{Examples.}')
    out.append('\\begin{itemize}[leftmargin=12pt,topsep=2pt,itemsep=1pt]')
    for ex in card['representative_oral']:
        out.append(
            f'  \\item \\textbf{{[Oral]}} \\texttt{{{latex_escape(ex["paper_id"])}}} '
            f'\\textemdash\\ {latex_escape(ex["one_sentence_why"])}'
        )
        if ex.get('lesson'):
            out.append(
                f'  \\\\ \\textcolor{{gray}}{{\\footnotesize \\textit{{Lesson:}} {latex_escape(ex["lesson"])}}}'
            )
    for ex in card['representative_reject']:
        out.append(
            f'  \\item \\textbf{{[Reject]}} \\texttt{{{latex_escape(ex["paper_id"])}}} '
            f'\\textemdash\\ {latex_escape(ex["one_sentence_why"])}'
        )
        if ex.get('lesson'):
            out.append(
                f'  \\\\ \\textcolor{{gray}}{{\\footnotesize \\textit{{Lesson:}} {latex_escape(ex["lesson"])}}}'
            )
    out.append('\\end{itemize}')
    out.append('\\end{tcolorbox}')
    out.append('')
    return '\n'.join(out)


def main():
    data = json.load(CARDS.open())
    cards_by_cid = data['cards_by_cluster_id']
    tax = json.load(TAX_PATH.open())['taxonomy']

    parts = ['% Auto-generated by paper/render_tactical.py',
             '% 47 tactical cards grouped by parent methodology.',
             '']

    # Group by parent
    for t in tax:
        mid = t['id']
        kids = [c for c in cards_by_cid.values() if c['parent_methodology_id'] == mid]
        if not kids:
            continue
        kids.sort(key=lambda c: c['cluster_id'])
        parts.append(f'\\subsection{{{latex_escape(t["name"])}}}')
        parts.append(f'\\textit{{Parent methodology id: \\texttt{{{latex_escape(mid)}}}; '
                     f'{len(kids)} tactical cluster{"" if len(kids)==1 else "s"}.}}')
        parts.append('')
        for c in kids:
            parts.append(render_card(c))

    OUT.write_text('\n'.join(parts))
    print(f'wrote {OUT} ({len(cards_by_cid)} cards)')


if __name__ == '__main__':
    main()
